pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="\\.\\.\\.master", replace="...v{{version}}", exactly=1},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
    {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased](https://github.com/badboy/iso8601/compare/v{{version}}...master) - ReleaseDate", exactly=1}
]
tag-name = "v{{version}}"
